name: Python application test with Github Actions

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3

    - name: Install dependencies
      run: |
        make install

    - name: Lint with Python
      run: |
        make lint

    - name: Test python
      run: |
        make test

    - name: format Python
      run: |
        make format
